#8
#(a)
lm.fit = lm(mpg~horsepower, data = Auto)
summary(lm.fit)
summary(Auto)
predict(lm.fit, data.frame(horsepower=98), interval = 'confidence')
predict(lm.fit, data.frame(horsepower=98), interval = 'prediction')
#(b)
plot(Auto$horsepower, Auto$mpg)
abline(lm.fit)
#(c)
par(mfrow=c(2,2))
plot(lm.fit)

#9
#(a)
pairs(Auto)
#(b)
cor(subset(Auto, select = -name))
#(c)
lm.fit = lm(mpg~.-name, data=Auto)
summary(lm.fit)
#(d)
plot(lm.fit)
par(mfrow=c(1,1))
plot(predict(lm.fit), rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
#(e)
lm.fit1 = lm(mpg~cylinders*displacement+cylinders:weight, data=Auto)
summary(lm.fit1)
#(f)
lm.fit2 = lm(mpg~sqrt(cylinders)+log(weight)+I(acceleration^2), data=Auto)
summary(lm.fit2)
par(mfrow=c(2,2))
plot(lm.fit2)
plot(predict(lm.fit2), rstudent(lm.fit2))

lm.fit3 = lm(log(mpg)~cylinders*weight+acceleration+year+origin, data=Auto)
summary(lm.fit3)
plot(lm.fit3)

#10
#(a)
library(ISLR)
lm.fit1 = lm(Sales~Price+Urban+US, data=Carseats)
summary(lm.fit1)
#(e)
lm.fit2 = lm(Sales~Price+US, data = Carseats)
summary(lm.fit2)
#(g)
confint(lm.fit2)
#(h)
par(mfrow=c(1,1))
plot(predict(lm.fit2), rstudent(lm.fit2))
plot(hatvalues(lm.fit2))

#11
set.seed(1)
x=rnorm(100)
y=2*x+rnorm(100)
#(a)
lm.fit = lm(y~x+0)
summary(lm.fit)
#(b)
lm.fit1 = lm(x~y+0)
summary(lm.fit1)
#(f)
lm.fit1 = lm(y~x)
lm.fit2 = lm(x~y)
summary(lm.fit1)
summary(lm.fit2)

#12
#(b)
set.seed(1)
x=rnorm(100)
y=2*x + rnorm(100)
lm.fit1 = lm(y~x)
lm.fit2 = lm(x~y)
summary(lm.fit1)
summary(lm.fit2)


#(c)
set.seed(1)
x=rnorm(100)
y=x
lm.fit1 = lm(y~x)
lm.fit2 = lm(x~y)
summary(lm.fit1)
summary(lm.fit2)

#13
#(a)
set.seed(1)
x=rnorm(100)

#(b)
eps=rnorm(100,0,0.5)

#(c)
y=-1+0.5*x+eps

#(d)
plot(x,y)

#(e)
lm.fit = lm(y~x)
summary(lm.fit)

#(f)
abline(lm.fit, lwd=3, col='red')
abline(-1, 0.5, lwd=3, col='blue')
legend('right',legend=c('least squared line', 'population regression'),col = c('red','blue'),lwd=3)

#(g)
lm.fit = lm(y~x+I(x^2))
summary(lm.fit)

#(h)
set.seed(1)
x=rnorm(100)
eps=rnorm(100,0,0.1)
y=-1+0.5*x+eps
plot(x,y)
lm.fit1 = lm(y~x)
summary(lm.fit1)
abline(lm.fit1, lwd=3, col='red')
abline(-1, 0.5, lwd=3, col='blue')
legend('right',legend=c('least squared line', 'population regression'),col = c('red','blue'),lwd=3)

#(i)
set.seed(1)
x=rnorm(100)
eps=rnorm(100,0,1)
y=-1+0.5*x+eps
plot(x,y)
lm.fit2 = lm(y~x)
summary(lm.fit2)
abline(lm.fit2, lwd=3, col='red')
abline(-1, 0.5, lwd=3, col='blue')
legend(-1,legend=c('least squared line', 'population regression'),col = c('red','blue'),lwd=3)

#(j)
confint(lm.fit)
confint(lm.fit1)
confint(lm.fit2)

#14
#(a)
set.seed(1)
x1=runif(100)
x2=0.5*x1+rnorm(100)/10
y=2+2*x1+0.3*x2+rnorm(100)

#(b)
cor(x1,x2)
plot(x1,x2)

#(c)
lm.fit = lm(y~x1+x2)
summary(lm.fit)

#(d)
lm.fit1 = lm(y~x1)
summary(lm.fit1)

#(e)
lm.fit2 = lm(y~x2)
summary(lm.fit2)

#(g)
x1=c(x1, 0.1)
x2=c(x2, 0.8)
y=c(y,6)
lm.fit = lm(y~x1+x2)
summary(lm.fit)
lm.fit1 = lm(y~x1)
summary(lm.fit1)
lm.fit2 = lm(y~x2)
summary(lm.fit2)
par(mfrow=c(2,2))
plot(lm.fit)
plot(lm.fit1)
plot(lm.fit2)
plot(predict(lm.fit),rstudent(lm.fit))
plot(predict(lm.fit1), rstudent(lm.fit1))
plot(predict(lm.fit2), rstudent(lm.fit2))
plot(hatvalues(lm.fit))
plot(hatvalues(lm.fit1))
plot(hatvalues(lm.fit2))

#15
#(a)
library(MASS)
summary(Boston)
Boston$chas <- as.factor(Boston$chas)
lm.fit1 = lm(crim~zn, data=Boston)
summary(lm.fit1)
lm.fit2 = lm(crim~indus, data=Boston)
summary(lm.fit2)
lm.fit3 = lm(crim~chas, data=Boston)
summary(lm.fit3)
lm.fit4 = lm(crim~nox, data=Boston)
summary(lm.fit4)
lm.fit5 = lm(crim~rm, data=Boston)
summary(lm.fit5)
lm.fit6 = lm(crim~age, data=Boston)
summary(lm.fit6)
lm.fit7 = lm(crim~dis, data=Boston)
summary(lm.fit7)
lm.fit8 = lm(crim~rad, data=Boston)
summary(lm.fit8)
lm.fit9 = lm(crim~tax, data=Boston)
summary(lm.fit9)
lm.fit10 = lm(crim~ptratio, data=Boston)
summary(lm.fit10)
lm.fit11 = lm(crim~black, data=Boston)
summary(lm.fit11)
lm.fit12 = lm(crim~lstat, data=Boston)
summary(lm.fit12)
lm.fit13 = lm(crim~medv, data=Boston)
summary(lm.fit13)

#(b)
lm.fit = lm(crim~., data=Boston)
summary(lm.fit)

#(c)
x <- c(coef(lm.fit1)[2], coef(lm.fit2)[2], coef(lm.fit3)[2], coef(lm.fit4)[2], coef(lm.fit5)[2], 
     coef(lm.fit6)[2], coef(lm.fit7)[2], coef(lm.fit8)[2], coef(lm.fit9)[2], coef(lm.fit10)[2],
     coef(lm.fit11)[2],coef(lm.fit12)[2],coef(lm.fit13)[2])
y <- c(coef(lm.fit)[-1])
par(mfrow=c(1,1))
plot(x,y)

#(d)
lm.zn = lm(crim~poly(zn,3),data=Boston)
summary(lm.zn)
lm.indus = lm(crim~poly(indus), data=Boston)
summary(lm.indus)
lm.nox = lm(crim~poly(nox), data=Boston)
summary(lm.nox)
lm.rm = lm(crim~poly(rm), data=Boston)
lm.age = lm(crim~poly(age), data=Boston)
summary(lm.age)
lm.dis = lm(crim~poly(dis), data=Boston)
summary(lm.dis)
lm.rad = lm(crim~poly(rad), data=Boston)
summary(lm.rad)
lm.tax = lm(crim~poly(tax), data=Boston)
summary(lm.tax)
lm.ptratio = lm(crim~poly(ptratio), data=Boston)
summary(lm.ptratio)
lm.black = lm(crim~poly(black), data=Boston)
summary(lm.black)
lm.lstat = lm(crim~poly(lstat), data=Boston)
summary(lm.lstat)
lm.medv = lm(crim~poly(medv), data=Boston)
summary(lm.medv)


